name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.13.4]
        otp: [24.3.3]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Compile Project
        run: mix compile

      - name: Run Tests
        run: mix test

      - name: Run Coveralls
        run: mix coveralls.json

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1       
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.11'
          otp-version: '22.3'

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Formatter
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo
